/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_branches"];
        put?: never;
        post: operations["create_branch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_branch"];
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_products"];
        put?: never;
        post: operations["create_product"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["match_products_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}/substitutes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_substitutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        patch: operations["update_user"];
        trace?: never;
    };
    "/api/v1/users/{id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assign_branches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assign_roles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verify_webhook_challenge"];
        put?: never;
        post: operations["handle_inbound_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssignBranchesRequest: {
            branch_ids: components["schemas"]["BranchId"][];
        };
        AssignRolesRequest: {
            role_names: string[];
        };
        AuthTokens: {
            access_token: string;
            /** Format: int64 */
            expires_in: number;
            refresh_token: string;
            token_type: string;
        };
        BranchDto: {
            address: string;
            city: string;
            code: string;
            cold_chain_capable: boolean;
            drap_licence_no: string;
            id: components["schemas"]["BranchId"];
            is_hub: boolean;
            name: string;
            pharmacist_in_charge: string;
            status: string;
            tenant_id: components["schemas"]["TenantId"];
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        BranchId: string;
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        CategoryId: string;
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        CreateBranchRequest: {
            address: string;
            city: string;
            code: string;
            cold_chain_capable: boolean;
            drap_licence_no: string;
            is_hub: boolean;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            name: string;
            pharmacist_in_charge: string;
        };
        CreateProductRequest: {
            barcode?: string | null;
            brand_name: string;
            category_id?: components["schemas"]["CategoryId"] | null;
            cost_price?: components["schemas"]["Money"] | null;
            dosage_form?: string | null;
            generic_name?: string | null;
            is_narcotic: boolean;
            is_prescription_only: boolean;
            is_refrigerated: boolean;
            manufacturer?: string | null;
            mrp: components["schemas"]["Money"];
            pack_size?: string | null;
            strength?: string | null;
            tp?: components["schemas"]["Money"] | null;
        };
        CreateUserRequest: {
            branch_ids: components["schemas"]["BranchId"][];
            email?: string | null;
            full_name: string;
            password: string;
            phone: string;
            role_names: string[];
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        GenericId: string;
        LoginRequest: {
            password: string;
            phone_or_email: string;
        };
        MatchCandidate: {
            brand_name: string;
            is_prescription_only: boolean;
            matched_on: string;
            method: components["schemas"]["MatchMethod"];
            mrp: components["schemas"]["Money"];
            product_id: components["schemas"]["ProductId"];
            /** Format: float */
            score: number;
            strength?: string | null;
        };
        /** @enum {string} */
        MatchMethod: "Exact" | "Alias" | "Trigram" | "Phonetic" | "Vector" | "Hybrid";
        MatchRequest: {
            /** Format: uuid */
            branch_id?: string | null;
            limit?: number;
            query: string;
        };
        /**
         * @description Monetary amount represented with exact precision using Decimal.
         *     Invariant I-8: All money is rust_decimal::Decimal. Never f64 or f32.
         *     Serializes over the wire as a quoted decimal string to preserve precision in frontend clients.
         * @example 1250.00
         */
        Money: string;
        ProductAliasDto: {
            alias: string;
            alias_type: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            hit_count: number;
            /** Format: uuid */
            id: string;
            product_id: components["schemas"]["ProductId"];
            script: string;
            source: string;
            /** Format: double */
            weight: number;
        };
        ProductDto: {
            barcode?: string | null;
            brand_name: string;
            cost_price?: components["schemas"]["Money"] | null;
            dosage_form?: string | null;
            generic_name?: string | null;
            id: components["schemas"]["ProductId"];
            is_narcotic: boolean;
            is_prescription_only: boolean;
            is_refrigerated: boolean;
            manufacturer?: string | null;
            mrp: components["schemas"]["Money"];
            pack_size?: string | null;
            status: string;
            strength?: string | null;
            tenant_id: components["schemas"]["TenantId"];
            tp?: components["schemas"]["Money"] | null;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        ProductId: string;
        RefreshRequest: {
            refresh_token: string;
        };
        RoleDto: {
            description?: string | null;
            id: components["schemas"]["RoleId"];
            is_system: boolean;
            name: string;
            permissions: string[];
            tenant_id: components["schemas"]["TenantId"];
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        RoleId: string;
        SubstitutionCandidate: {
            brand_name: string;
            equivalence_type: string;
            generic_name: string;
            mrp: components["schemas"]["Money"];
            product_id: components["schemas"]["ProductId"];
            requires_pharmacist_approval: boolean;
            savings_vs_original: components["schemas"]["Money"];
            strength: string;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        TenantId: string;
        UpdateBranchRequest: {
            address?: string | null;
            cold_chain_capable?: boolean | null;
            is_hub?: boolean | null;
            name?: string | null;
            pharmacist_in_charge?: string | null;
            status?: string | null;
        };
        UpdateProductRequest: {
            barcode?: string | null;
            brand_name?: string | null;
            cost_price?: components["schemas"]["Money"] | null;
            dosage_form?: string | null;
            generic_name?: string | null;
            is_narcotic?: boolean | null;
            is_prescription_only?: boolean | null;
            is_refrigerated?: boolean | null;
            manufacturer?: string | null;
            mrp?: components["schemas"]["Money"] | null;
            pack_size?: string | null;
            status?: string | null;
            strength?: string | null;
            tp?: components["schemas"]["Money"] | null;
        };
        UpdateUserRequest: {
            email?: string | null;
            full_name?: string | null;
            locale?: string | null;
            status?: string | null;
        };
        UserDto: {
            branch_ids: components["schemas"]["BranchId"][];
            /** Format: date-time */
            created_at: string;
            email?: string | null;
            full_name: string;
            id: components["schemas"]["UserId"];
            /** Format: date-time */
            last_login_at?: string | null;
            locale: string;
            phone: string;
            roles: string[];
            status: string;
            tenant_id: components["schemas"]["TenantId"];
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        UserId: string;
        UserProfileResponse: {
            permissions: string[];
            user: components["schemas"]["UserDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile and permissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Password validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Invalid or revoked refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_branches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List branches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDto"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_branch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBranchRequest"];
            };
        };
        responses: {
            /** @description Branch created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_branch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Branch ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBranchRequest"];
            };
        };
        responses: {
            /** @description Branch updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Branch not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all permissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_products: {
        parameters: {
            query?: {
                /** @description Search query */
                q?: string | null;
                /** @description Limit */
                limit?: number | null;
                /** @description Offset */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_product: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Product created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    match_products_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Matching candidate products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchCandidate"][];
                };
            };
        };
    };
    get_product: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_substitutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Substitution candidates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubstitutionCandidate"][];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User soft deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assign_branches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignBranchesRequest"];
            };
        };
        responses: {
            /** @description Branches assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assign_roles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRolesRequest"];
            };
        };
        responses: {
            /** @description Roles assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_webhook_challenge: {
        parameters: {
            query?: {
                /** @description Hub mode */
                "hub.mode"?: string | null;
                /** @description Hub verify token */
                "hub.verify_token"?: string | null;
                /** @description Hub challenge */
                "hub.challenge"?: string | null;
            };
            header?: never;
            path: {
                /** @description Channel ID */
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook challenge verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Verification token mismatch */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    handle_inbound_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel ID */
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Inbound webhook acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid signature */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
