/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ai/analyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyse_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/draft-reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["draft_reply_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["feedback_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transcribe_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_branches"];
        put?: never;
        post: operations["create_branch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_branch"];
        trace?: never;
    };
    "/api/v1/canned-replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_canned_reply_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_conversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inbound_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assign_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claim_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["send_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transfer_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adjust_stock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/cold-chain/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["log_cold_chain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/cold-chain/{batch_id}/clear-excursion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clear_excursion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receive_stock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_stock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/transfers/{id}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dispatch_transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/bulk-approve/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulk_approve_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["override_message_handler"];
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_orders"];
        put?: never;
        post: operations["create_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_order"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/confirm-cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm_cart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transition_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_products"];
        put?: never;
        post: operations["create_product"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["match_products_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}/substitutes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_substitutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        patch: operations["update_user"];
        trace?: never;
    };
    "/api/v1/users/{id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assign_branches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assign_roles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verify_webhook_challenge"];
        put?: never;
        post: operations["handle_inbound_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddOrderItemRequest: {
            discount?: components["schemas"]["Money"] | null;
            product_id: components["schemas"]["ProductId"];
            /** Format: int32 */
            qty: number;
            unit_price?: components["schemas"]["Money"] | null;
        };
        AiAnalyseRequest: {
            contains_controlled_substance: boolean;
            conversation_id: components["schemas"]["ConversationId"];
            is_rx_context: boolean;
            message_id: components["schemas"]["MessageId"];
            raw_text: string;
        };
        AiDraftReplyRequest: {
            conversation_id: components["schemas"]["ConversationId"];
            customer_name?: string | null;
            is_rx_context: boolean;
            last_inbound_text: string;
        };
        AiHealthStatus: {
            /** Format: int32 */
            failure_count: number;
            state: string;
            task: string;
        };
        /** @enum {string} */
        AiTask: "Intent" | "Reply" | "RxOcr" | "Stt" | "Embed";
        AiTranscribeRequest: {
            audio_url: string;
            /** Format: int32 */
            duration_seconds: number;
            locale_hint?: string | null;
            message_id: components["schemas"]["MessageId"];
        };
        AnalysisResult: {
            /** Format: float */
            confidence: number;
            detected_script: components["schemas"]["CustomerScript"];
            entities: components["schemas"]["ExtractedEntity"][];
            escalate: boolean;
            escalation_reason?: string | null;
            intent: components["schemas"]["IntentType"];
            normalised_text: string;
        };
        AssignBranchesRequest: {
            branch_ids: components["schemas"]["BranchId"][];
        };
        AssignConversationRequest: {
            user_id: components["schemas"]["UserId"];
        };
        AssignRolesRequest: {
            role_names: string[];
        };
        AuthTokens: {
            access_token: string;
            /** Format: int64 */
            expires_in: number;
            refresh_token: string;
            token_type: string;
        };
        BatchAllocation: {
            batch_id: components["schemas"]["BatchId"];
            batch_number: string;
            /** Format: date */
            expiry_date: string;
            /** Format: int32 */
            qty: number;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        BatchId: string;
        BranchAvailabilityDto: {
            branch_id: components["schemas"]["BranchId"];
            branch_name: string;
            can_fulfill_all: boolean;
            /** Format: int32 */
            total_available: number;
        };
        BranchDto: {
            address: string;
            city: string;
            code: string;
            cold_chain_capable: boolean;
            drap_licence_no: string;
            id: components["schemas"]["BranchId"];
            is_hub: boolean;
            name: string;
            pharmacist_in_charge: string;
            status: string;
            tenant_id: components["schemas"]["TenantId"];
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        BranchId: string;
        CannedReplyDto: {
            body_en: string;
            body_ur?: string | null;
            body_ur_latn?: string | null;
            /** Format: uuid */
            id: string;
            shortcode: string;
            title: string;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        CategoryId: string;
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        ClearExcursionRequest: {
            decision_note: string;
        };
        ColdChainLogRequest: {
            batch_id: components["schemas"]["BatchId"];
            branch_id: components["schemas"]["BranchId"];
            note?: string | null;
            /** Format: double */
            temperature_c: number;
        };
        ConversationDto: {
            assigned_to?: components["schemas"]["UserId"] | null;
            branch_id?: components["schemas"]["BranchId"] | null;
            /** Format: date-time */
            created_at: string;
            customer_id: components["schemas"]["CustomerId"];
            id: components["schemas"]["ConversationId"];
            is_rx_linked: boolean;
            /** Format: date-time */
            last_message_at?: string | null;
            status: string;
            tenant_id: components["schemas"]["TenantId"];
            /** Format: int32 */
            unread_count: number;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        ConversationId: string;
        CreateBranchRequest: {
            address: string;
            city: string;
            code: string;
            cold_chain_capable: boolean;
            drap_licence_no: string;
            is_hub: boolean;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            name: string;
            pharmacist_in_charge: string;
        };
        CreateCannedReplyRequest: {
            body_en: string;
            body_ur?: string | null;
            body_ur_latn?: string | null;
            branch_id?: components["schemas"]["BranchId"] | null;
            shortcode: string;
            title: string;
        };
        CreateDraftOrderRequest: {
            branch_id?: components["schemas"]["BranchId"] | null;
            customer_id: components["schemas"]["CustomerId"];
            payment_method?: string | null;
        };
        CreateProductRequest: {
            barcode?: string | null;
            brand_name: string;
            category_id?: components["schemas"]["CategoryId"] | null;
            cost_price?: components["schemas"]["Money"] | null;
            dosage_form?: string | null;
            generic_name?: string | null;
            is_narcotic: boolean;
            is_prescription_only: boolean;
            is_refrigerated: boolean;
            manufacturer?: string | null;
            mrp: components["schemas"]["Money"];
            pack_size?: string | null;
            strength?: string | null;
            tp?: components["schemas"]["Money"] | null;
        };
        CreateTransferRequest: {
            items: components["schemas"]["TransferItemRequest"][];
            note?: string | null;
            source_branch_id: components["schemas"]["BranchId"];
            target_branch_id: components["schemas"]["BranchId"];
        };
        CreateUserRequest: {
            branch_ids: components["schemas"]["BranchId"][];
            email?: string | null;
            full_name: string;
            password: string;
            phone: string;
            role_names: string[];
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        CustomerId: string;
        /** @enum {string} */
        CustomerScript: "Urdu" | "English" | "RomanUrdu" | "CodeMixed";
        DraftReplyResult: {
            can_auto_send: boolean;
            /** Format: float */
            confidence: number;
            draft_body: string;
            escalate: boolean;
            requires_pharmacist: boolean;
        };
        ExtractedEntity: {
            /** Format: float */
            confidence: number;
            entity_type: string;
            value: string;
        };
        FeedbackEventRequest: {
            ai_output: string;
            /** Format: float */
            confidence: number;
            conversation_id: components["schemas"]["ConversationId"];
            corrected_alias?: (string)[] | null;
            human_output: string;
            intent: string;
            message_id: components["schemas"]["MessageId"];
            prompt_version: string;
            task: string;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        GenericId: string;
        InboundMessageRequest: {
            branch_id?: components["schemas"]["BranchId"] | null;
            /** Format: uuid */
            channel_id?: string | null;
            display_name?: string | null;
            msisdn: string;
            text: string;
        };
        /** @enum {string} */
        IntentType: "ProductEnquiry" | "PriceEnquiry" | "AvailabilityCheck" | "PlaceOrder" | "OrderStatus" | "CancelOrder" | "PrescriptionUpload" | "DeliveryEnquiry" | "PaymentQuery" | "Complaint" | "Greeting" | "HumanRequest" | "Other";
        LoginRequest: {
            password: string;
            phone_or_email: string;
        };
        MatchCandidate: {
            brand_name: string;
            is_prescription_only: boolean;
            matched_on: string;
            method: components["schemas"]["MatchMethod"];
            mrp: components["schemas"]["Money"];
            product_id: components["schemas"]["ProductId"];
            /** Format: float */
            score: number;
            strength?: string | null;
        };
        /** @enum {string} */
        MatchMethod: "Exact" | "Alias" | "Trigram" | "Phonetic" | "Vector" | "Hybrid";
        MatchRequest: {
            /** Format: uuid */
            branch_id?: string | null;
            limit?: number;
            query: string;
        };
        MessageDto: {
            body: string;
            conversation_id: components["schemas"]["ConversationId"];
            /** Format: date-time */
            created_at: string;
            direction: string;
            id: components["schemas"]["MessageId"];
            original_body?: string | null;
            overridden_by?: components["schemas"]["UserId"] | null;
            /** Format: uuid */
            sender_id?: string | null;
            sender_type: string;
            status: string;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        MessageId: string;
        /**
         * @description Monetary amount represented with exact precision using Decimal.
         *     Invariant I-8: All money is rust_decimal::Decimal. Never f64 or f32.
         *     Serializes over the wire as a quoted decimal string to preserve precision in frontend clients.
         * @example 1250.00
         */
        Money: string;
        OrderDto: {
            branch_id?: components["schemas"]["BranchId"] | null;
            /** Format: date-time */
            created_at: string;
            customer_id: components["schemas"]["CustomerId"];
            delivery_fee: components["schemas"]["Money"];
            discount: components["schemas"]["Money"];
            id: components["schemas"]["OrderId"];
            is_rx_linked: boolean;
            items: components["schemas"]["OrderItemDto"][];
            order_no: string;
            payment_method: string;
            payment_status: string;
            status: components["schemas"]["OrderStatus"];
            subtotal: components["schemas"]["Money"];
            tax_amount: components["schemas"]["Money"];
            tenant_id: components["schemas"]["TenantId"];
            total: components["schemas"]["Money"];
        };
        OrderEventDto: {
            actor_id?: components["schemas"]["UserId"] | null;
            /** Format: date-time */
            created_at: string;
            from_status?: string | null;
            /** Format: uuid */
            id: string;
            order_id: components["schemas"]["OrderId"];
            reason?: string | null;
            to_status: string;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        OrderId: string;
        OrderItemDto: {
            /** Format: uuid */
            id: string;
            is_prescription_only: boolean;
            is_refrigerated: boolean;
            line_discount: components["schemas"]["Money"];
            line_total: components["schemas"]["Money"];
            mrp_at_sale: components["schemas"]["Money"];
            product_id: components["schemas"]["ProductId"];
            product_name: string;
            /** Format: int32 */
            qty: number;
            unit_price: components["schemas"]["Money"];
        };
        /** @enum {string} */
        OrderStatus: "Draft" | "CartConfirmed" | "AwaitingRx" | "RxUnderReview" | "RxApproved" | "RxRejected" | "AwaitingPayment" | "PaymentUnderReview" | "PaymentRejected" | "Confirmed" | "Picking" | "Packed" | "Dispatched" | "OutForDelivery" | "Delivered" | "CashReconciled" | "Closed" | "Cancelled" | "FailedDelivery" | "Returned" | "Refunded";
        OverrideMessageRequest: {
            new_body: string;
        };
        ProductAliasDto: {
            alias: string;
            alias_type: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            hit_count: number;
            /** Format: uuid */
            id: string;
            product_id: components["schemas"]["ProductId"];
            script: string;
            source: string;
            /** Format: double */
            weight: number;
        };
        ProductDto: {
            barcode?: string | null;
            brand_name: string;
            cost_price?: components["schemas"]["Money"] | null;
            dosage_form?: string | null;
            generic_name?: string | null;
            id: components["schemas"]["ProductId"];
            is_narcotic: boolean;
            is_prescription_only: boolean;
            is_refrigerated: boolean;
            manufacturer?: string | null;
            mrp: components["schemas"]["Money"];
            pack_size?: string | null;
            status: string;
            strength?: string | null;
            tenant_id: components["schemas"]["TenantId"];
            tp?: components["schemas"]["Money"] | null;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        ProductId: string;
        RefreshRequest: {
            refresh_token: string;
        };
        ReturnItemRequest: {
            is_safe_to_restock: boolean;
            /** Format: uuid */
            item_id: string;
            note?: string | null;
            pharmacist_certified: boolean;
            /** Format: int32 */
            qty: number;
        };
        RoleDto: {
            description?: string | null;
            id: components["schemas"]["RoleId"];
            is_system: boolean;
            name: string;
            permissions: string[];
            tenant_id: components["schemas"]["TenantId"];
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        RoleId: string;
        SendMessageRequest: {
            body: string;
            is_template: boolean;
            template_name?: string | null;
        };
        StockAdjustmentRequest: {
            batch_id: components["schemas"]["BatchId"];
            branch_id: components["schemas"]["BranchId"];
            product_id: components["schemas"]["ProductId"];
            /** Format: int32 */
            qty_delta: number;
            reason: string;
        };
        StockCurrentDto: {
            batch_id: components["schemas"]["BatchId"];
            batch_number: string;
            branch_id: components["schemas"]["BranchId"];
            /** Format: date */
            expiry_date: string;
            is_quarantined: boolean;
            product_id: components["schemas"]["ProductId"];
            /** Format: int32 */
            qty: number;
        };
        StockReceiptRequest: {
            batch_number: string;
            branch_id: components["schemas"]["BranchId"];
            cost_price?: components["schemas"]["Money"] | null;
            /** Format: date */
            expiry_date: string;
            product_id: components["schemas"]["ProductId"];
            /** Format: int32 */
            qty: number;
            /** Format: uuid */
            supplier_id?: string | null;
        };
        SubstitutionCandidate: {
            brand_name: string;
            equivalence_type: string;
            generic_name: string;
            mrp: components["schemas"]["Money"];
            product_id: components["schemas"]["ProductId"];
            requires_pharmacist_approval: boolean;
            savings_vs_original: components["schemas"]["Money"];
            strength: string;
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        TenantId: string;
        TranscriptionResult: {
            /** Format: float */
            confidence: number;
            /** Format: int32 */
            duration_seconds: number;
            escalate: boolean;
            escalation_reason?: string | null;
            normalised_transcript: string;
            transcript: string;
        };
        TransferConversationRequest: {
            branch_id: components["schemas"]["BranchId"];
        };
        TransferDto: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            source_branch_id: components["schemas"]["BranchId"];
            status: string;
            target_branch_id: components["schemas"]["BranchId"];
            tenant_id: components["schemas"]["TenantId"];
        };
        TransferItemRequest: {
            batch_id: components["schemas"]["BatchId"];
            product_id: components["schemas"]["ProductId"];
            /** Format: int32 */
            qty: number;
        };
        TransitionOrderRequest: {
            reason?: string | null;
            to_status: components["schemas"]["OrderStatus"];
        };
        UpdateBranchRequest: {
            address?: string | null;
            cold_chain_capable?: boolean | null;
            is_hub?: boolean | null;
            name?: string | null;
            pharmacist_in_charge?: string | null;
            status?: string | null;
        };
        UpdateProductRequest: {
            barcode?: string | null;
            brand_name?: string | null;
            cost_price?: components["schemas"]["Money"] | null;
            dosage_form?: string | null;
            generic_name?: string | null;
            is_narcotic?: boolean | null;
            is_prescription_only?: boolean | null;
            is_refrigerated?: boolean | null;
            manufacturer?: string | null;
            mrp?: components["schemas"]["Money"] | null;
            pack_size?: string | null;
            status?: string | null;
            strength?: string | null;
            tp?: components["schemas"]["Money"] | null;
        };
        UpdateUserRequest: {
            email?: string | null;
            full_name?: string | null;
            locale?: string | null;
            status?: string | null;
        };
        UserDto: {
            branch_ids: components["schemas"]["BranchId"][];
            /** Format: date-time */
            created_at: string;
            email?: string | null;
            full_name: string;
            id: components["schemas"]["UserId"];
            /** Format: date-time */
            last_login_at?: string | null;
            locale: string;
            phone: string;
            roles: string[];
            status: string;
            tenant_id: components["schemas"]["TenantId"];
        };
        /**
         * Format: uuid
         * @example 018f3a9e-4c5b-7b3a-9e1a-2b3c4d5e6f7a
         */
        UserId: string;
        UserProfileResponse: {
            permissions: string[];
            user: components["schemas"]["UserDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyse_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiAnalyseRequest"];
            };
        };
        responses: {
            /** @description Message analysis results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
        };
    };
    draft_reply_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiDraftReplyRequest"];
            };
        };
        responses: {
            /** @description Draft reply generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftReplyResult"];
                };
            };
        };
    };
    feedback_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackEventRequest"];
            };
        };
        responses: {
            /** @description Feedback recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Circuit breaker status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiHealthStatus"][];
                };
            };
        };
    };
    transcribe_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiTranscribeRequest"];
            };
        };
        responses: {
            /** @description Audio transcribed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResult"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile and permissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Password validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Invalid or revoked refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_branches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List branches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDto"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_branch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBranchRequest"];
            };
        };
        responses: {
            /** @description Branch created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_branch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Branch ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBranchRequest"];
            };
        };
        responses: {
            /** @description Branch updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Branch not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_canned_reply_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCannedReplyRequest"];
            };
        };
        responses: {
            /** @description Canned reply created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CannedReplyDto"];
                };
            };
        };
    };
    list_conversations: {
        parameters: {
            query?: {
                /** @description Filter by branch ID */
                branch_id?: string | null;
                /** @description Filter by status */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDto"][];
                };
            };
        };
    };
    inbound_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboundMessageRequest"];
            };
        };
        responses: {
            /** @description Processed inbound message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDto"];
                };
            };
        };
    };
    assign_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignConversationRequest"];
            };
        };
        responses: {
            /** @description Conversation assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    claim_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation claimed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Outbound message sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDto"];
                };
            };
        };
    };
    transfer_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferConversationRequest"];
            };
        };
        responses: {
            /** @description Conversation transferred */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adjust_stock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockAdjustmentRequest"];
            };
        };
        responses: {
            /** @description Stock adjusted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    log_cold_chain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColdChainLogRequest"];
            };
        };
        responses: {
            /** @description Temperature logged */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clear_excursion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Batch ID */
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClearExcursionRequest"];
            };
        };
        responses: {
            /** @description Excursion cleared by pharmacist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    receive_stock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockReceiptRequest"];
            };
        };
        responses: {
            /** @description Stock received and movement recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchId"];
                };
            };
        };
    };
    list_stock: {
        parameters: {
            query?: {
                /** @description Filter by branch ID */
                branch_id?: string | null;
                /** @description Filter by product ID */
                product_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current stock list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockCurrentDto"][];
                };
            };
        };
    };
    create_transfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransferRequest"];
            };
        };
        responses: {
            /** @description Transfer draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferDto"];
                };
            };
        };
    };
    dispatch_transfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transfer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transfer dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferDto"];
                };
            };
        };
    };
    bulk_approve_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID */
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bulk approved non-Rx drafts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    override_message_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Message ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideMessageRequest"];
            };
        };
        responses: {
            /** @description Draft message overridden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDto"];
                };
            };
        };
    };
    list_orders: {
        parameters: {
            query?: {
                /** @description Filter by branch ID */
                branch_id?: string | null;
                /** @description Filter by order status */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"][];
                };
            };
        };
    };
    create_order: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftOrderRequest"];
            };
        };
        responses: {
            /** @description Draft order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
        };
    };
    get_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
        };
    };
    confirm_cart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
        };
    };
    add_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddOrderItemRequest"];
            };
        };
        responses: {
            /** @description Item added to order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
        };
    };
    transition_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionOrderRequest"];
            };
        };
        responses: {
            /** @description Order state transitioned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
        };
    };
    list_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all permissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_products: {
        parameters: {
            query?: {
                /** @description Search query */
                q?: string | null;
                /** @description Limit */
                limit?: number | null;
                /** @description Offset */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_product: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Product created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    match_products_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Matching candidate products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchCandidate"][];
                };
            };
        };
    };
    get_product: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_substitutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Substitution candidates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubstitutionCandidate"][];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User soft deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assign_branches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignBranchesRequest"];
            };
        };
        responses: {
            /** @description Branches assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assign_roles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRolesRequest"];
            };
        };
        responses: {
            /** @description Roles assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_webhook_challenge: {
        parameters: {
            query?: {
                /** @description Hub mode */
                "hub.mode"?: string | null;
                /** @description Hub verify token */
                "hub.verify_token"?: string | null;
                /** @description Hub challenge */
                "hub.challenge"?: string | null;
            };
            header?: never;
            path: {
                /** @description Channel ID */
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook challenge verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Verification token mismatch */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    handle_inbound_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel ID */
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Inbound webhook acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid signature */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
